apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service 
  namespace: {{ .Values.namespace }}
  labels:
  app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.adminPort }}
      protocol: TCP
      name: admin
    - port: {{ .Values.service.listener1 }}
      protocol: TCP
      name: listener1
    - port: {{ .Values.service.listener2 }}
      protocol: TCP
      name: listener2 
  selector:
    app: {{ .Release.Name }}
