apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: teamserver-gateway
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
    - port:
        number: 80
        name: http-system
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 50050 # exposes teamserver admin port
        name: tcp-admin
        protocol: TCP
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: PASSTHROUGH
      hosts:
        - "*"
