apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: teamserver-virtual-service
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - teamserver-gateway
  http:
    - match:
        - headers:
            user-agent:
              regex: "Trident\/7\.0;\srv:11\.0"
          uri:
            prefix: "/zC"
      route:
        - destination:
            host: teamserver1-service
    - route:
      - destination:
          host: www.google.com
  tls:
    - match:
        - port: 443
          sni_hosts:
            - kube.cccco.net
      route:
        - destination:
            host: teamserver1-service
            port:
              number: 443
    - route:
      - destination:
          host: www.google.com
          port: 443