apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: admin-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Release.Name }}-gateway
  tcp:
    - match:
        - port: 50050
      route:
        - destination:
            host: {{ .Release.Name }}-service
            port:
              number: 50050
