apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: silenttrinity-virtual-service
spec:
  hosts:
    - "*"
  gateways:
    - silenttrinity-gateway
  tcp:
    - match:
        - port: 443
      route:
        - destination:
            host: silenttrinity1-service
            port:
              number: 443