apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service 
  namespace: {{ .Values.namespace }}
  labels:
  app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: st-port
    - port: {{ .Values.service.listener1 }}
      protocol: TCP
      name: listener1
  selector:
    app: {{ .Release.Name }}
