apiVersion: apps/v1
kind: Deployment
metadata:
  name: gophish
spec:
  selector:
    matchLabels:
      app: gophish
  replicas: 1
  template:
    metadata:
      labels:
        app: gophish
    spec:
      containers:
        - name: gophish
          image: larrysuto/gophish:gophish-kr
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: gophish-service
  namespace: default
  labels:
    app: gophish
spec:
  type: ClusterIP
  ports:
    - port: 3333
      protocol: TCP
      name: st-port
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: gophish
