apiVersion: v1
kind: Service
metadata:
  name: gophish-service
  namespace: Default
  labels:
    app: gophish
spec:
  type: ClusterIP
  ports:
    - port: 3333
      protocol: TCP
      name: st-port
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: gophish
